// Mocks generated by Mockito 5.4.4 from annotations
// in islamic_app/test/prayer_times_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i3;

import 'package:geolocator/geolocator.dart' as _i8;
import 'package:islamic_app/models/ayah.dart' as _i13;
import 'package:islamic_app/models/azkar.dart' as _i14;
import 'package:islamic_app/models/hadith.dart' as _i7;
import 'package:islamic_app/models/prayer_times.dart' as _i5;
import 'package:islamic_app/models/qibla.dart' as _i6;
import 'package:islamic_app/models/surah.dart' as _i4;
import 'package:islamic_app/models/user_settings.dart' as _i2;
import 'package:islamic_app/providers/settings_provider.dart' as _i9;
import 'package:islamic_app/services/api_service.dart' as _i12;
import 'package:islamic_app/services/location_service.dart' as _i15;
import 'package:islamic_app/services/notification_service.dart' as _i17;
import 'package:islamic_app/services/storage_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserSettings_0 extends _i1.SmartFake implements _i2.UserSettings {
  _FakeUserSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_1 extends _i1.SmartFake implements _i3.Locale {
  _FakeLocale_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSurah_2 extends _i1.SmartFake implements _i4.Surah {
  _FakeSurah_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrayerTimes_3 extends _i1.SmartFake implements _i5.PrayerTimes {
  _FakePrayerTimes_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQiblaDirection_4 extends _i1.SmartFake
    implements _i6.QiblaDirection {
  _FakeQiblaDirection_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHadithCollection_5 extends _i1.SmartFake
    implements _i7.HadithCollection {
  _FakeHadithCollection_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHadith_6 extends _i1.SmartFake implements _i7.Hadith {
  _FakeHadith_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_7 extends _i1.SmartFake implements _i8.Position {
  _FakePosition_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i9.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeUserSettings_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.UserSettings);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  _i3.Locale get locale => (super.noSuchMethod(
        Invocation.getter(#locale),
        returnValue: _FakeLocale_1(
          this,
          Invocation.getter(#locale),
        ),
      ) as _i3.Locale);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setThemeMode(int? themeMode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [themeMode],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleDarkMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleDarkMode,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setCalculationMethod(int? method) => (super.noSuchMethod(
        Invocation.method(
          #setCalculationMethod,
          [method],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setMadhab(int? madhab) => (super.noSuchMethod(
        Invocation.method(
          #setMadhab,
          [madhab],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setPrayerNotification(
    String? prayer,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPrayerNotification,
          [
            prayer,
            enabled,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setNotificationAdvanceMinutes(int? minutes) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationAdvanceMinutes,
          [minutes],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setQuranAudioAutoPlay(bool? autoPlay) =>
      (super.noSuchMethod(
        Invocation.method(
          #setQuranAudioAutoPlay,
          [autoPlay],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setQuranReciter(String? reciter) => (super.noSuchMethod(
        Invocation.method(
          #setQuranReciter,
          [reciter],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setQuranFontSize(double? size) => (super.noSuchMethod(
        Invocation.method(
          #setQuranFontSize,
          [size],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setShowTranslation(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTranslation,
          [show],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setTranslationLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTranslationLanguage,
          [language],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setShowTafsir(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTafsir,
          [show],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setTafsirSource(String? source) => (super.noSuchMethod(
        Invocation.method(
          #setTafsirSource,
          [source],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setHapticFeedback(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setHapticFeedback,
          [enabled],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setReduceMotion(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setReduceMotion,
          [enabled],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateLocation({
    required double? latitude,
    required double? longitude,
    required String? city,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #city: city,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setLocationPermissionGranted(bool? granted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLocationPermissionGranted,
          [granted],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setCompassCalibrated(bool? calibrated) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCompassCalibrated,
          [calibrated],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i12.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i4.Surah>> getAllSurahs({String? edition = r'ar'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSurahs,
          [],
          {#edition: edition},
        ),
        returnValue: _i11.Future<List<_i4.Surah>>.value(<_i4.Surah>[]),
      ) as _i11.Future<List<_i4.Surah>>);

  @override
  _i11.Future<_i4.Surah> getSurah(
    int? number, {
    String? edition = r'ar',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurah,
          [number],
          {#edition: edition},
        ),
        returnValue: _i11.Future<_i4.Surah>.value(_FakeSurah_2(
          this,
          Invocation.method(
            #getSurah,
            [number],
            {#edition: edition},
          ),
        )),
      ) as _i11.Future<_i4.Surah>);

  @override
  _i11.Future<List<_i13.Ayah>> getSurahAyahs(
    int? surahNumber, {
    String? edition = r'ar',
    String? translationEdition = r'en.sahih',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurahAyahs,
          [surahNumber],
          {
            #edition: edition,
            #translationEdition: translationEdition,
          },
        ),
        returnValue: _i11.Future<List<_i13.Ayah>>.value(<_i13.Ayah>[]),
      ) as _i11.Future<List<_i13.Ayah>>);

  @override
  _i11.Future<String> getAyahAudio(
    int? ayahNumber,
    String? reciter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAyahAudio,
          [
            ayahNumber,
            reciter,
          ],
        ),
        returnValue: _i11.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getAyahAudio,
            [
              ayahNumber,
              reciter,
            ],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i5.PrayerTimes> getPrayerTimes({
    required double? latitude,
    required double? longitude,
    int? method = 3,
    int? school = 0,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayerTimes,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #method: method,
            #school: school,
            #date: date,
          },
        ),
        returnValue: _i11.Future<_i5.PrayerTimes>.value(_FakePrayerTimes_3(
          this,
          Invocation.method(
            #getPrayerTimes,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #method: method,
              #school: school,
              #date: date,
            },
          ),
        )),
      ) as _i11.Future<_i5.PrayerTimes>);

  @override
  _i11.Future<_i5.PrayerTimes> getPrayerTimesByCity({
    required String? city,
    required String? country,
    int? method = 3,
    int? school = 0,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayerTimesByCity,
          [],
          {
            #city: city,
            #country: country,
            #method: method,
            #school: school,
            #date: date,
          },
        ),
        returnValue: _i11.Future<_i5.PrayerTimes>.value(_FakePrayerTimes_3(
          this,
          Invocation.method(
            #getPrayerTimesByCity,
            [],
            {
              #city: city,
              #country: country,
              #method: method,
              #school: school,
              #date: date,
            },
          ),
        )),
      ) as _i11.Future<_i5.PrayerTimes>);

  @override
  _i11.Future<_i6.QiblaDirection> getQiblaDirection({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQiblaDirection,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue:
            _i11.Future<_i6.QiblaDirection>.value(_FakeQiblaDirection_4(
          this,
          Invocation.method(
            #getQiblaDirection,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i11.Future<_i6.QiblaDirection>);

  @override
  _i11.Future<List<_i7.HadithCollection>> getHadithCollections() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHadithCollections,
          [],
        ),
        returnValue: _i11.Future<List<_i7.HadithCollection>>.value(
            <_i7.HadithCollection>[]),
      ) as _i11.Future<List<_i7.HadithCollection>>);

  @override
  _i11.Future<_i7.HadithCollection> getHadithCollection(
    String? collectionId, {
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHadithCollection,
          [collectionId],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i11.Future<_i7.HadithCollection>.value(_FakeHadithCollection_5(
          this,
          Invocation.method(
            #getHadithCollection,
            [collectionId],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i11.Future<_i7.HadithCollection>);

  @override
  _i11.Future<_i7.Hadith> getHadith(
    String? collectionId,
    String? hadithId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHadith,
          [
            collectionId,
            hadithId,
          ],
        ),
        returnValue: _i11.Future<_i7.Hadith>.value(_FakeHadith_6(
          this,
          Invocation.method(
            #getHadith,
            [
              collectionId,
              hadithId,
            ],
          ),
        )),
      ) as _i11.Future<_i7.Hadith>);

  @override
  _i11.Future<List<_i7.Hadith>> searchHadith({
    required String? query,
    String? collectionId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchHadith,
          [],
          {
            #query: query,
            #collectionId: collectionId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i11.Future<List<_i7.Hadith>>.value(<_i7.Hadith>[]),
      ) as _i11.Future<List<_i7.Hadith>>);

  @override
  _i11.Future<List<_i14.AzkarCategory>> getAzkarCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAzkarCategories,
          [],
        ),
        returnValue:
            _i11.Future<List<_i14.AzkarCategory>>.value(<_i14.AzkarCategory>[]),
      ) as _i11.Future<List<_i14.AzkarCategory>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i15.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i8.Position> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i11.Future<_i8.Position>.value(_FakePosition_7(
          this,
          Invocation.method(
            #getCurrentLocation,
            [],
          ),
        )),
      ) as _i11.Future<_i8.Position>);

  @override
  _i11.Future<bool> hasLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasLocationPermission,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<void> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<_i8.Position?> getLastKnownLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLastKnownLocation,
          [],
        ),
        returnValue: _i11.Future<_i8.Position?>.value(),
      ) as _i11.Future<_i8.Position?>);

  @override
  _i11.Stream<_i8.Position> getPositionStream({
    _i8.LocationAccuracy? accuracy = _i8.LocationAccuracy.high,
    int? distanceFilter = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPositionStream,
          [],
          {
            #accuracy: accuracy,
            #distanceFilter: distanceFilter,
          },
        ),
        returnValue: _i11.Stream<_i8.Position>.empty(),
      ) as _i11.Stream<_i8.Position>);

  @override
  _i11.Future<Map<String, dynamic>> getLocationInfo() => (super.noSuchMethod(
        Invocation.method(
          #getLocationInfo,
          [],
        ),
        returnValue:
            _i11.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i11.Future<Map<String, dynamic>>);

  @override
  double calculateDistance(
    double? lat1,
    double? lon1,
    double? lat2,
    double? lon2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateDistance,
          [
            lat1,
            lon1,
            lat2,
            lon2,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double calculateBearing(
    double? lat1,
    double? lon1,
    double? lat2,
    double? lon2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBearing,
          [
            lat1,
            lon1,
            lat2,
            lon2,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i11.Future<void> saveLocationToSettings(
    _i2.UserSettings? settings, {
    required double? latitude,
    required double? longitude,
    required String? city,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocationToSettings,
          [settings],
          {
            #latitude: latitude,
            #longitude: longitude,
            #city: city,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i16.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i17.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }
}
